# Generated by Django 3.2.7 on 2021-09-28 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('author', models.IntegerField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('blog', models.TextField()),
            ],
        ),
    ]
