# Generated by Django 3.2.7 on 2021-09-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_task_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='blog',
            field=models.TextField(blank=True),
        ),
    ]
